### ISSUE TITLE
File skipping with (-d) isn't working and reuploads the file

### ISSUE THREAD

**Issue by Anon-Exploiter** [labbots/google-drive-upload#101]
Hi, 

Thanks for the awesome script, wasn't able to find shared drive uploading functionality in many overrated scripts. 

I just noticed that `-d` is supposed to skip the file if it is uploaded already but that doesn't happen (I'm sure that's the intended functionality), the script creates a new file regardless of the file existing and this will happen as many times as we execute the command. 

Here are some screenshots to help explain the issue. 

**Uploading:** 

![image](https://user-images.githubusercontent.com/18597330/89839403-0dfd6680-db87-11ea-85ff-7345f1bf7702.png)

**POC:**

![image](https://user-images.githubusercontent.com/18597330/89839415-15247480-db87-11ea-9e95-820ec09fb933.png)

---

**Environment:**

**OS:** Ubuntu 18.04 LTS 
**Uploading to**: Google Shared Drive

Let me know if further information is required to reproduce the issue.

**Comment by Anon-Exploiter** [comment]
Another file with some data in it (in case there is any check of size of files):

![image](https://user-images.githubusercontent.com/18597330/89839685-d04d0d80-db87-11ea-931b-25e640f12740.png)

**Comment by Akianonymus** [comment]
Weird, it works just fine here

```
❯  gupload -p 1 -V -v -R 5 test -d -c test                 
================[ Workspace Folder: test ]=================
------------ ********************************* ------------

===================[ Given Input: FILE ]===================
=============[ Upload Method: Skip Existing ]==============

======================[ test | 0 B ]=======================
----------------------[ Uploading.. ]----------------------
  % Total     % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:-- --:-100   117  100   117    0     0    105      0  0:00:01  0:00:01 --:--:--   105
=================[ test | 0 B | Uploaded ]=================
-----------------------[ DriveLink ]-----------------------
                           ^ ^ ^
https://drive.google.com/open?id=*******

========= Time Elapsed: 0 minute(s) and 4 seconds =========

~
❯  gupload -p 1 -V -v -R 5 test -d -c test
================[ Workspace Folder: test ]=================
------------ ******************************** ------------

===================[ Given Input: FILE ]===================
=============[ Upload Method: Skip Existing ]==============

=================[ test already exists. ]==================
-----------------------[ DriveLink ]-----------------------
                           ^ ^ ^
https://drive.google.com/open?id=********

========= Time Elapsed: 0 minute(s) and 1 seconds ========
```

One more thing, that your DriveLink is not showing after upload

Anyway, run below commands and give me the log1 and log2 file
( upload in some paste site or gist )

```shell
printf "" >> test123test
gupload test123test -o -D &> log1
gupload test123test -d -D &> log2

for i in log1 log2; do
    values="$(grep -oE "(CLIENT_ID|CLIENT_SECRET|REFRESH_TOKEN|ACCESS_TOKEN|ROOT_FOLDER|WORKSPACE_FOLDER_ID)=.*" "${i}")"
    eval "${values}"

    for j in CLIENT_ID CLIENT_SECRET REFRESH_TOKEN ACCESS_TOKEN ROOT_FOLDER WORKSPACE_FOLDER_ID; do
         string="$(eval printf "%s" \"\$"${j}"\")"
        sed "s|${string}|"*****"|g" -i "${i}"
    done
done
```

**Comment by Anon-Exploiter** [comment]
Yeah, I noticed the pretty-printing isn't happening either. Here are the log files 

**Log1:** https://del.dog/raw/ivuyriphai
**Log2:** https://del.dog/raw/bawifogohu

It again uploaded both files on shared google drive. 

![image](https://user-images.githubusercontent.com/18597330/89866715-73724700-dbc9-11ea-8501-cd717e11eb72.png)

**Comment by Akianonymus** [comment]
> Yeah, I noticed the pretty-printing isn't happening either. Here are the log files
> 
> **Log1:** https://del.dog/raw/ivuyriphai
> **Log2:** https://del.dog/raw/bawifogohu
> 
> It again uploaded both files on shared google drive.
> 
> ![image](https://user-images.githubusercontent.com/18597330/89866715-73724700-dbc9-11ea-8501-cd717e11eb72.png)

So, it is not able to search files, probably because of team drive

i pushed some fixes, run below command to pull the fixes and try again

```
curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh | sh -s -- -B wip
```

**Comment by Anon-Exploiter** [comment]
Hi, 

Reinstalled using the above command and it is still the same. Here are some POCs regarding that: 

**Reinstallation (after updating once):**

![image](https://user-images.githubusercontent.com/18597330/89885858-213f1f00-dbe5-11ea-9470-506cadebbabc.png)


**Uploading:**

![image](https://user-images.githubusercontent.com/18597330/89885769-fc4aac00-dbe4-11ea-8215-366b3bc370ae.png)

**On Gdrive:**

![image](https://user-images.githubusercontent.com/18597330/89885790-02408d00-dbe5-11ea-8680-e191d367df33.png)

**Comment by Anon-Exploiter** [comment]
@Akianonymus maybe the commits weren't pushed? 

The file shows it was updated 2 days ago (from the master branch):

![image](https://user-images.githubusercontent.com/18597330/89886330-e38ec600-dbe5-11ea-8ef2-695faa03853d.png)

**Comment by Anon-Exploiter** [comment]
Also, the last commit was 8 hours ago: 

![image](https://user-images.githubusercontent.com/18597330/89886476-1f299000-dbe6-11ea-9a3b-10b02f793ccd.png)

**Comment by Akianonymus** [comment]
```
curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh | sh -s -- -B wip
```

If you look closely, -B flag is used, which fetches the installation from branch, in this case, will be wip ( i pushed the changes to wip branch ).

anyway, try again, i forgot to push a local change.

**Comment by Akianonymus** [comment]
Also, provide the logs again if it doesn't work.

**Comment by Anon-Exploiter** [comment]
My bad, I just looked at the first part. 

Here's the logs, the issue is still not fixed: 

**Log1:** https://del.dog/raw/pestucyfoh
**Log2:** https://del.dog/raw/afuthester

**Comment by Akianonymus** [comment]
@Anon-Exploiter Update and try again, should be working this time ( i tested my self on a team drive ).

**Comment by Anon-Exploiter** [comment]
@Akianonymus, it's still the same, here are the logs. 

**Log1:** https://del.dog/raw/odubighucr
**Log2:** https://del.dog/raw/mehestuned

**Comment by Akianonymus** [comment]
@Anon-Exploiter Hmm, alright

Tell me exactly how you did the setup. Also, specifically details related to the team drive things.

This is what i did.

I just created a shared drive, made a folder, and used it as root folder. -d flag was not working, but after the fix i applied, it started.

( are you on telegram ? conversation would be much easier there, no push though, here is fine too, just this bug is bugging me 😂 and i wanna fix it fast )

**Comment by Anon-Exploiter** [comment]
@Akianonymus hahaha, yeah sure. Same here, I almost consumed 500GB+ upload depending on the skip flag :sweat_smile: 

I'm on discord: Umar_0x01#0079

Let me try the latest commit you've done as well. 

Also, I can give you contributor access to my shared drive for testing xD Let's continue it in discord.

**Comment by Anon-Exploiter** [comment]
Also, for the initial installation, I used the one-liner from here: 
https://github.com/labbots/google-drive-upload#basic-method

I've created a Ubuntu 18.04 LTS instance on AWS and am testing on that since. Details: 

```bash
~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by Anon-Exploiter** [comment]
Here's the .googledriveconf global configuration.

![image](https://user-images.githubusercontent.com/18597330/89916526-231ed780-dc11-11ea-8c9c-abb4493c1d3c.png)

**Comment by Akianonymus** [comment]
@Anon-Exploiter Check discord.

**Comment by Anon-Exploiter** [comment]
Done, added.

**Comment by Akianonymus** [comment]
A new release is created: https://github.com/labbots/google-drive-upload/releases/tag/v3.3.1

**Comment by Anon-Exploiter** [comment]
Thanks for the support, works fine now! :man_dancing:
